{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-simple-api
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.rules }}
    - http:
        paths:
          - pathType: {{ .pathType }}
            path: {{ .path }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
    {{- end }}
{{- end }}
