nameOverride: ""
fullnameOverride: ""
replicaCount: 1
revisions: 3

strategy:
  type: rollingUpdate
  maxSurge: 1
  maxUnavailable: 1

image:
  repository: docker.io/alexbatista26/api
  pullPolicy: IfNotPresent
  tag: ""

containerPort:
  - 8080
  - 443

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: 128Mi
    cpu: "200m"
  requests:
    memory: 64Mi
    cpu: "100m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  rules:
    - pathType: "Prefix"
      path: "/api/"
      service:
        name: "simple-api"
        port: 8080